name: "Antora Site"
description: "Generate the Antora site"
branding:
  icon: book-open
  color: yellow
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: false
  antora_lunr_docsearch_enabled:
    description: 'Select whether to enable lunr documentation search'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.antora_playbook}}
    - ${{ inputs.site_sources_path }}
    - ${{ inputs.antora_lunr_docsearch_enabled }}
