#!/bin/bash 

set -o pipefail
set -eu 

echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
echo "GITHUB_WORKSPACE: $GITHUB_RUNNER_WORKSPACE"

ls -ltr $GITHUB_WORKSPACE

ls -ltr $GITHUB_RUNNER_WORKSPACE

cd $GITHUB_WORKSPACE

antora --stacktrace $INPUT_ANTORA_PLAYBOOK