= Antora Site GitHub Action

GitHub action that can be used to generate the https://antora.org/[Antora] site.

It supports as opt-in the https://github.com/Mogztter/antora-site-generator-lunr[Lunr] index generator for documentation search.

== Parameters

The action accepts the following parameters:
 
* `antora_playbook` -- that specifies the Antora playbook path within the repository
* `site_sources_path` -- the path within `$GITHUB_WORKSPACE` from where to run the site generation
* `antora_generator` -- Select antora generator for site
* `antora_docsearch_enabled` -- Flag for enabling antora docsearch
* `antora_docsearch_index_version` -- Select the document version to be indexed

== How to add to your action

[source,yaml]
----
name: "Generate site using antora site action"
uses: kameshsampath/antora-site-action@v0.3.0
with:
    antora_playbook: antora-playbook.yml
    # optional path within the repo, defaults to ${{github.workspace}}
    site_sources_path: 'site-sources-folder'
----

A complete example is available https://github.com/kameshsampath/antora-test-site[here].

== How to add to your action for Lunr documentation search index

[source,yaml]
----
name: "Generate site and doc search index using antora site action"
uses: kameshsampath/antora-site-action@v0.3.0
with:
    antora_playbook: antora-playbook.yml
    # optional path within the repo, defaults to ${{github.workspace}}
    site_sources_path: 'site-sources-folder'
    antora_generator: 'antora-site-generator-lunr'
    antora_docsearch_enabled: 'true'
----

A complete example using Lunr is available https://github.com/camptocamp/devops-stack/blob/master/.github/workflows/website.yml#L31[here].
